Bootstrap3/Controllers/StreamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bootstrap3.Controllers
{
    public class StreamController : Controller
    {
        // GET: Stream
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BuildTwitterStream()
        {

            return View();
        }

        public ActionResult ViewSavedTwitterStreams()
        {

            return View();
        }
    }
}

Bootstrap3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Customer Relationship Management System To Analyze Twitter Data">
    <meta name="author" content="Coderthemes">

    <link rel="shortcut icon" href="~/Content/images/favicon_1.ico">

    <title>Twitter CRM System</title>

    <!-- Base Css Files -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Font Icons -->
    <link href="~/Content/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/assets/ionicon/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/Content/css/material-design-iconic-font.min.css" rel="stylesheet">

    <!-- animate css -->
    <link href="~/Content/css/animate.css" rel="stylesheet" />

    <!-- Waves-effect -->
    <link href="~/Content/css/waves-effect.css" rel="stylesheet">

    <!-- sweet alerts -->
    <link href="~/Content/assets/sweet-alert/sweet-alert.min.css" rel="stylesheet">

    <!-- Custom Files -->
    <link href="~/Content/css/helper.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="~/Scripts/modernizr.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <link rel="stylesheet" href="~/Content/assets/jquery-datatables-editable/datatables.css" />
    <link rel="stylesheet" href="~/Content/assets/magnific-popup/magnific-popup.css" />
    <link href="~/Content/assets/responsive-table/rwd-table.min.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="~/Content/assets/tagsinput/jquery.tagsinput.css" rel="stylesheet" />

</head>
<body class="fixed-left">

    <!-- Begin page -->
    <div id="wrapper">

        <!-- Top Bar Start -->
        @Html.Partial("_NavBar")
        <!-- Top Bar End -->
        <!-- ========== Left Sidebar Start ========== -->
        @Html.Partial("_LeftSideBar")
        <!-- Left Sidebar End -->
            

        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="content-page">
            <!-- Start content -->
            <div class="content">
                <div class="container">


                     @RenderBody()



                </div> <!-- container -->

            </div> <!-- content -->

            <footer class="footer text-right">
                2015 © Moltran.
            </footer>

        </div>

        <!-- ============================================================== -->
        <!-- End Right content here -->
        <!-- ============================================================== -->
        <!-- Right Sidebar #Html.Partial("_RightSideBar")  -->
      
        <!-- /Right-bar -->

        <div id="dialog" class="modal-block mfp-hide">
            <section class="panel panel-info panel-color">
                <header class="panel-heading">
                    <h2 class="panel-title">Are you sure?</h2>
                </header>
                <div class="panel-body">
                    <div class="modal-wrapper">
                        <div class="modal-text">
                            <p>Are you sure that you want to delete this row?</p>
                        </div>
                    </div>

                    <div class="row m-t-20">
                        <div class="col-md-12 text-right">
                            <button id="dialogConfirm" class="btn btn-primary">Confirm</button>
                            <button id="dialogCancel" class="btn btn-default">Cancel</button>
                        </div>
                    </div>
                </div>

            </section>
        </div>




    </div>
    
    <!-- container -->



    <script>
            var resizefunc = [];
    </script>


    <!-- jQuery  -->
 
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/waves.js"></script>
    <script src="~/Scripts/wow.min.js"></script>
    <script src="~/Scripts/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.scrollTo.min.js"></script>
    <script src="~/Content/assets/chat/moment-2.2.1.js"></script>
    <script src="~/Content/assets/jquery-sparkline/jquery.sparkline.min.js"></script>
    <script src="~/Content/assets/jquery-detectmobile/detect.js"></script>
    <script src="~/Content/assets/fastclick/fastclick.js"></script>
    <script src="~/Content/assets/jquery-slimscroll/jquery.slimscroll.js"></script>
    <script src="~/Content/assets/jquery-blockui/jquery.blockUI.js"></script>

    <!-- sweet alerts -->
    <script src="~/Content/assets/sweet-alert/sweet-alert.min.js"></script>
    <script src="~/Content/assets/sweet-alert/sweet-alert.init.js"></script>

    <!-- flot Chart
    <script src="~/Content/assets/flot-chart/jquery.flot.js"></script>
    <script src="~/Content/assets/flot-chart/jquery.flot.time.js"></script>
    <script src="~/Content/assets/flot-chart/jquery.flot.tooltip.min.js"></script>
    <script src="~/Content/assets/flot-chart/jquery.flot.resize.js"></script>
    <script src="~/Content/assets/flot-chart/jquery.flot.pie.js"></script>
    <script src="~/Content/assets/flot-chart/jquery.flot.selection.js"></script>
    <script src="~/Content/assets/flot-chart/jquery.flot.stack.js"></script>
    <script src="~/Content/assets/flot-chart/jquery.flot.crosshair.js"></script>
    <script src="~/Content/assets/flot-chart/jquery.flot.init.js"></script>
         -->

    <!-- Counter-up -->
    <script src="~/Content/assets/counterup/waypoints.min.js" type="text/javascript"></script>
    <script src="~/Content/assets/counterup/jquery.counterup.min.js" type="text/javascript"></script>

    <!-- CUSTOM JS -->
    <script src="~/Scripts/jquery.app.js"></script>
    <script src="~/Content/assets/responsive-table/rwd-table.min.js" type="text/javascript"></script>
    <script src="~/Content/assets/tagsinput/jquery.tagsinput.min.js"></script>

    <!-- Dashboard -->
    <script src="~/Scripts/jquery.dashboard.js"></script>

    <!-- DataTable -->
    <script src="~/Content/assets/jquery-datatables-editable/jquery.dataTables.js"></script>
    <script src="~/Content/assets/datatables/dataTables.bootstrap.js"></script>
    <script src="~/Content/assets/jquery-datatables-editable/datatables.editable.init.js"></script>
    <script src="~/Content/assets/magnific-popup/magnific-popup.js"></script>

   

    <!-- Todo -->
    <script src="~/Scripts/jquery.todo.js"></script>

    <script type="text/javascript">
        /* ==============================================
        Counter Up
        =============================================== */
        jQuery(document).ready(function ($) {
            $('.counter').counterUp({
                delay: 100,
                time: 1200
            });
        });
    </script>

    <script>
        jQuery(document).ready(function() {

            // Tags Input
            jQuery('#tags').tagsInput({width:'auto'});
        });
           
    </script>

    @RenderSection("scripts", required: false)
</body>

</html>

Bootstrap3/Views/Shared/_LeftSideBar.cshtml
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <div class="user-details">
           
            <div class="user-info">
                <div class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Company 1<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="javascript:void(0)"><i class="md md-face-unlock"></i> Manage Profile<div class="ripple-wrapper"></div></a></li>
                        <li><a href="javascript:void(0)"><i class="md md-settings-power"></i> Logout </a></li>
                    </ul>
                </div>

            </div>
        </div>
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
                <li>                  
                    <a href="@Url.Action("Index", "Home")" > <i class="md md-home"></i><span> Dashboard </span></a>
                </li>

                <li class="has_sub">
                    <a href="@Url.Action("Index", "Stream")" class="waves-effect"><i class="md md-view-list"></i><span> Twitter Live Streams </span><span class="pull-right"><i class="md md-view-list"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("BuildTwitterStream", "Stream")">Build Stream</a></li>
                        <li><a href="@Url.Action("ViewSavedTwitterStreams","Stream")">View Saved Streams</a></li>
                    </ul>
                </li>

                <li>
                    <a href="@Url.Action("ViewAllCustomers", "Customers")" > <i class="md md-account-child"></i><span> View All Customers </span><span class="pull-right"><i class="md  md-account-child"></i></span></a>

                </li>

                <li>
                    <a href="#" class="waves-effect"><i class="md md-call-received"></i><span> Import Customers </span><span class="pull-right"><i class="md  md-call-received"></i></span></a>

                </li>

                <li>
                    <a href="#" class="waves-effect"><i class="md md-call-made"></i><span> Export Customers Data</span><span class="pull-right"><i class="md  md-call-made"></i></span></a>
                </li>

            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

Bootstrap3/Views/Shared/_NavBar.cshtml
<div class="topbar">
    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center">
            <a href="@Url.Action("Index","Home")" class="logo"><i class="md md-terrain"></i> <span> Twitter CRM  </span></a>
        </div>
    </div>
    <!-- Button mobile view to collapse sidebar menu -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="">

                <div class="pull-left">
                    <button class="button-menu-mobile open-left">
                        <i class="fa fa-bars"></i>
                    </button>
                    <span class="clearfix"></span>
                </div>
              

            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>